mifos_users_response = [
    {
        "id": 1,
        "accountNo": "000000001",
        "status": {"id": 300, "code": "clientStatusType.active", "value": "Active"},
        "subStatus": {"active": False, "mandatory": False},
        "active": True,
        "activationDate": [2021, 12, 26],
        "firstname": "bharath",
        "lastname": "c",
        "displayName": "bharath c",
        "mobileNo": "8466970674",
        "gender": {"active": False, "mandatory": False},
        "clientType": {"active": False, "mandatory": False},
        "clientClassification": {"active": False, "mandatory": False},
        "isStaff": False,
        "officeId": 1,
        "officeName": "Head Office",
        "timeline": {
            "submittedOnDate": [2021, 12, 10],
            "submittedByUsername": "mifos",
            "submittedByFirstname": "App",
            "submittedByLastname": "Administrator",
            "activatedOnDate": [2021, 12, 26],
            "activatedByUsername": "mifos",
            "activatedByFirstname": "App",
            "activatedByLastname": "Administrator",
        },
        "clientNonPersonDetails": {
            "constitution": {"active": False, "mandatory": False},
            "mainBusinessLine": {"active": False, "mandatory": False},
        },
    },
    {
        "id": 3,
        "accountNo": "000000006",
        "status": {"id": 300, "code": "clientStatusType.active", "value": "Active"},
        "subStatus": {"active": False, "mandatory": False},
        "active": True,
        "activationDate": [2021, 12, 26],
        "firstname": "Pavan Sri",
        "middlename": "Hari",
        "lastname": "eatg",
        "displayName": "Pavan Sri Hari eatg",
        "gender": {"active": False, "mandatory": False},
        "clientType": {"id": 15, "name": "Pavan", "active": False, "mandatory": False},
        "clientClassification": {"active": False, "mandatory": False},
        "isStaff": False,
        "officeId": 1,
        "officeName": "Head Office",
        "timeline": {
            "submittedOnDate": [2021, 12, 23],
            "submittedByUsername": "mifos",
            "submittedByFirstname": "App",
            "submittedByLastname": "Administrator",
            "activatedOnDate": [2021, 12, 26],
            "activatedByUsername": "mifos",
            "activatedByFirstname": "App",
            "activatedByLastname": "Administrator",
        },
        "clientNonPersonDetails": {
            "constitution": {"active": False, "mandatory": False},
            "mainBusinessLine": {"active": False, "mandatory": False},
        },
    },
]

excepted_user_list = [
    {
        "client_id": 1,
        "full_name": "bharath c",
        "status": {"id": 300, "code": "clientStatusType.active", "value": "Active"},
        "mobile_number": "8466970674",
        "office_name": "Head Office",
    }
]
