# Generated by Django 2.2 on 2022-01-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.IntegerField()),
                ("full_name", models.CharField(max_length=50)),
                ("status", models.TextField()),
                ("mobile_number", models.CharField(max_length=20)),
                ("office_name", models.CharField(max_length=50)),
            ],
        )
    ]
